---
- name: File System Reduction
  hosts: db_servers, app_servers
  remote_user: ansadmin
  become: true
  tasks:
        -  name: Unmounting the file system
           mount: 
                 path: /data
                 state: unmounted
        -  name: Reducing the logical volume along with file system
           lvol: 
                vg: datavg
                lv: datalv
                size: 50%VG
                resizefs: yes
                force: yes
        -  name: mounting the file system
           mount: 
                 path: /data
                 src: /dev/datavg/datalv
                 fstype: ext4
                 state: mounted
        -  name: Reducing the pv from vg
           shell: vgreduce datavg /dev/sdc1
        -  name: Removing the partitions of /dev/sdc disk
           parted:
                  device: /dev/sdc
                  number: 1
                  state: absent 
