---
- name: unsharing the nfs file system
  hosts: app_servers, db_servers, sai-ansiblesrv
  remote_user: ansadmin
  become: true
  vars:
       - logical_volumes: 
                - {lv: 'webdatalv1'}
                - {lv: 'webdatalv2'}
                - {lv: 'webdatalv3'}
       - mount_points:
                - {path: '/saiwebdata1'}
                - {path: '/saiwebdata2'}
                - {path: '/saiwebdata3'}
  tasks:
        -  name: removing entries in /etc/exports file
           lineinfile:
                      path: /etc/exports
                      regexp: 'webdata'
                      state: absent
        -  name: reloading the /etc/exports file
           shell: sudo exportfs -avr
        -  name: unmounting the file system
           mount:
                 path: '{{item.path}}'
                 state: absent
           with_items:
                      - '{{mount_points}}'
        -  name: removing the logical volume1
           lvol:
                vg: webvg
                lv: webdatalv1
                state: absent
                force: yes
        -  name: removing the logical volume2
           lvol:
                vg: webvg
                lv: webdatalv2
                state: absent
                force: yes
        -  name: removing the logical volume2
           lvol:
                vg: webvg
                lv: webdatalv3
                state: absent
                force: yes
        -  name: removing the volume groups
           lvg:
               vg: webvg
               state: absent
        -  name: unpartion the disk
           parted:
                  device: /dev/sdd
                  number: 1
                  state: absent
                                