---
- name: Repo Configuration Rhel7.4
  hosts: sai-ansiblesrv, sai-client1, sai-client2
  remote_user: ansadmin
  become: true
  tasks:
        -  name: Removing rhel7.4 directory
           file:
                path: /var/ftp/pub/rhel7.4
                state: absent
        -  name: removing repo file
           file:
                path: /etc/yum.repos.d/rhe74.repo
                state: absent

