---
- name: zsh configuration setup
  hosts: sai-client2,sai-client1,sai-ansiblesrv
  remote_user: ansadmin
  become: true
  tasks:
    -  name : install zsh package
       yum:
          name: zsh
          state: latest

